app/Http/routes.php
<?php

// ================================================================================================================================
// routes.php
// --------------------------------------------------------------------------------------------------------------------------------
// Polymorphix Gaming: Stellar Clicker
// https://github.com/angelahnicole/Stellar-Clicker-Web
// @author Angela Gross
// --------------------------------------------------------------------------------------------------------------------------------
// Routes to direct web application to desired views.
// ================================================================================================================================

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Route::group(['middleware' => ['web', 'sentinel.auth']], function () 
{
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    // --------------------------------------------------------------------------------------------------------------------------
    // BLOG SUBDOMAIN
    // --------------------------------------------------------------------------------------------------------------------------
    Route::group(['domain' => 'blog.stellar.polymorphixgaming.com'], function () 
    {
        // -------------------------------------------------------------------------------
        // MAIN BLOG ROUTES
        // -------------------------------------------------------------------------------
        Route::group(['as' => 'blog::'], function () 
        {
            Route::get('', 'PostController@index')->name('home');
            
            // ---------------------------------------------------------------------------
            // POST RESOURCE CONTROLLER
            // Contains routes for index, create, store, show, edit, update, and destroy
            // ---------------------------------------------------------------------------
            Route::resource('post', 'PostController');
            Route::get('post/manage/all', 'PostController@manage')->name('post.manage');
            
            // ---------------------------------------------------------------------------
            // USER RESOURCE CONTROLLER
            // Handles logging in, registering, redirecting users to their home page, and
            // contains routes for create, store, edit, update, and destroy
            // ---------------------------------------------------------------------------
            Route::resource("user", "UserController", ['except' => ['show', 'index', 'create']]);
            Route::group(['as' => 'user.'], function () 
            {
                // Logging in and out
                Route::get('user/login', 'UserController@login')->name('login');
                Route::post('user/login', 'UserController@validateLogin')->name('validateLogin');
                Route::get('user/logout', 'UserController@logout')->name('logout');
                
                // Password reset
                Route::get('user/password/email', 'UserController@createReset')->name('createReset');
                Route::post('user/password/email', 'UserController@storeReset')->name('storeReset');
                Route::get('user/password/reset/{id}/{token}', 'UserController@editPassword')->name('editPassword');
                Route::post('user/password/reset/{id}/{token}', 'UserController@updatePassword')->name('updatePassword');
                
                // User administration
                Route::get('user/manage/all', 'UserController@manage')->name('manage');
            });
        });
        
        // -------------------------------------------------------------------------------
        // API ROUTES
        // -------------------------------------------------------------------------------
        Route::group(['prefix' => 'api'], function () 
        {
            // ---------------------------------------------------------------------------
            // POST COMMENT RESOURCE CONTROLLER
            // Contains nested resource routes for index, store, update, and destroy
            // ---------------------------------------------------------------------------
            Route::resource('post.comment', 'PostCommentController', ['except' => ['create', 'edit', 'show']]);
        });
        
    });
    
    // --------------------------------------------------------------------------------------------------------------------------
    // WIKI SUBDOMAIN
    // --------------------------------------------------------------------------------------------------------------------------
    Route::group(['domain' => 'wiki.stellar.polymorphixgaming.com'], function () 
    {
        Route::group(['as' => 'wiki::'], function () 
        {
            Route::get('', 'HomeController@wikiHome')->name('home');
        });
    });

    // --------------------------------------------------------------------------------------------------------------------------
    // STELLAR CLICKER SUBDOMAIN
    // --------------------------------------------------------------------------------------------------------------------------
    Route::group(['domain' => 'stellar.polymorphixgaming.com'], function () 
    {
        Route::group(['as' => 'stellar::'], function () 
        {
            Route::get('', 'HomeController@stellarHome')->name('home');
        });
    });
    
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
});

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

resources/views/blog/blog.blade.php
@extends('master.master')

<!-- CONTENT -->
@section('content')


<section class="window" id="home">
    
    <div class="redirect-container">
        <a href="{{ url()->previous() }}" alt="Redirect Back Link" title="Redirect Back Link"><span class="glyphicon glyphicon-menu-left"></span> Back</a>
    </div>

    
    <div class="front-page-header"><div class="row">
        <div class="col-xs-1"><div class="front-page-tag"><span class="glyphicon icon-tag"></div></div>
        <div class="col-xs-11"><h2>{{ $post->title_text }}<small>{{ $post->user->username }} // {{ $post->created_at->format('M j, Y') }}</small></h2></div>
            
            
    </div></div>
    
    <div class="front-page-panel">
                
        {!!  Markdown::convertToHtml($post->body_text) !!}
        
        <hr/>
        
        @if(\Sentinel::guest())
        
        <div class="row"><div class="col-md-12">
            <a class="btn btn-default btn-block" href="{{ route('blog::user.login') }}" style="margin-bottom:10px">
                <i class="fa fa-btn fa-sign-in"></i> Login to Comment
            </a>
        </div></div>
        
        @endif
        
        <div id="comments-container"></div>

                
    </div>
    
    
    
</section> 


@stop

@section('scripts')
@parent

<script>
    
    
    $(document).ready(function()
    {
        $.ajaxSetup
        ({
            headers: 
            {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        
        $('#comments-container').comments
        ({
            enableUpvoting: false,
            enableEditing: true,
            @if(\Sentinel::guest())
            enableReplying: false,
            @endif
            
            fieldMappings: 
            {
                id: 'id',
                parent: 'blog_comment_parent_id',
                created: 'created_at',
                modified: 'updated_at',
                content: 'body_text',
                fullname: 'username',
                createdByAdmin: 'created_by_admin',
                createdByCurrentUser: 'created_by_current_user'
            },
            
            getComments: function(success, error) 
            {
                var getURL = "{{ route('api.post.comment.index', ['post' => $post->id]) }}";
                
                $.ajax
                ({
                    type: 'get',
                    url: getURL,
                    success: function(commentsArray) 
                    {
                        success(commentsArray);
                    },
                    error: error
                });

            },
            
            postComment: function(commentJSON, success, error) 
            {
                var postURL = "{{ route('api.post.comment.store', ['post' => $post->id]) }}";
                
                $.ajax
                ({
                    type: 'post',
                    url: postURL,
                    data: commentJSON,
                    success: function(comment) 
                    {
                        success(comment);
                    },
                    error: error
                });

            },
            
            putComment: function(commentJSON, success, error) 
            {
                var putURL = "/api/post/{{ $post->id }}/comment/" + commentJSON.id;
                
                $.ajax
                ({
                    type: 'put',
                    url: putURL,
                    data: commentJSON,
                    success: function(comment) 
                    {
                        success(comment);
                    },
                    error: error
                });
            },
            
            deleteComment: function(commentJSON, success, error) 
            {
                var deleteURL = "/api/post/{{ $post->id }}/comment/" + commentJSON.id;
                
                $.ajax
                ({
                    type: 'delete',
                    url: deleteURL,
                    success: success,
                    error: error
                });
            }
        });
        
        @if(\Sentinel::guest())

        $(window).load(function()
        {
           disableReplying(); 
        });

        @endif
    });
    
</script>



@stop

<!-- /CONTENT -->

resources/views/blog/home.blade.php
@extends('master.master')

<!-- ASSETS -->
@section('assets')

@parent

<link rel="stylesheet" href="{{ asset('css/blog.css') }}">

@stop
<!-- /ASSETS -->

<!-- CONTENT -->
@section('content')


<section class="window" id="home">
    
    <div class="container-fluid text-center">
        {!! $posts->render() !!}
    </div>
    
    @foreach ($posts as $post)
    
    <div class="front-page-header"><div class="row">
        <div class="col-xs-1"><div class="front-page-tag"><span class="glyphicon icon-tag"></div></div>
        <div class="col-xs-11"><h2>{{ $post->title_text }}<small>{{ $post->user->username }} // {{ $post->created_at->format('M j, Y') }}</small></h2></div>
    </div></div>
    
    <div class="front-page-panel">
        
        
                
        {!! Markdown::convertToHtml($post->body_text) !!}
        
        @if($user = \Sentinel::check())
        
            @if($user->inRole('admin') || $user->inRole('blogger'))
            
                <hr>
                
                <a href="{{ route('blog::post.edit' , ['post' => $post->id]) }}" class="text-uppercase pull-right" alt="Edit Blog Post Link" title="Edit Blog Post Link">Edit</a>
                
                <br><br>
                
             
            @endif
        
        @endif
        
    </div>
    
    <div class="comment-link-panel">
        
        <a href="{{ route('blog::post.show', ['post' => $post->id]) }}" alt="Full Post Link" title="Full Post Link">Full Post and Comments</a>
        
    </div>
    
    @endforeach
    
    <div class="container-fluid text-center">
        {!! $posts->render() !!}
    </div>
    
</section> 


@stop
<!-- /CONTENT -->